/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistema_inventarios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author misael
 */
public class Reporte_Irregularidad extends javax.swing.JPanel {

    /**
     * Creates new form Reporte_Irregularidad
     */
    public Reporte_Irregularidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcodigoproducto = new javax.swing.JTextField();
        txttrabajador = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtproblema = new javax.swing.JTextArea();
        fecha = new com.toedter.calendar.JDateChooser();
        almacen = new javax.swing.JComboBox<>();
        txtcodigoreporte = new javax.swing.JTextField();
        btnsubir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Reporte de Irregularidad");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Codigo del Reporte:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Trabajador:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Seleccione Almacen:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Codigo del Producto:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Producto:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Descripcion del Problema:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ingrese Fecha:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        txtcodigoproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoproductoActionPerformed(evt);
            }
        });
        add(txtcodigoproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 170, 30));
        add(txttrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, 30));

        txtproducto.setEditable(false);
        add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 170, 30));

        txtcantidad.setEditable(false);
        add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 170, 30));

        txtproblema.setColumns(20);
        txtproblema.setRows(5);
        jScrollPane1.setViewportView(txtproblema);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 240, 130));
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 140, 30));

        almacen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", " " }));
        add(almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 170, 30));
        add(txtcodigoreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 40, 40));

        btnsubir.setText("Enviar");
        add(btnsubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 100, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reporte/vidrio-de-aumento (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String codigoProducto = txtcodigoproducto.getText();

        if (codigoProducto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un código de producto.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventarios", "root", "")) {
            String query = "SELECT producto, stock FROM almacen1 WHERE codigoproducto = ? AND stock >= 0";

            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, codigoProducto);

                try (ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        txtproducto.setText(resultSet.getString("producto"));
                        txtcantidad.setText(String.valueOf(resultSet.getInt("stock")));
                    } else {
                        JOptionPane.showMessageDialog(this, "Producto no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcodigoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoproductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> almacen;
    public javax.swing.JButton btnsubir;
    public com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    public javax.swing.JTextField txtcantidad;
    public javax.swing.JTextField txtcodigoproducto;
    public javax.swing.JTextField txtcodigoreporte;
    public javax.swing.JTextArea txtproblema;
    public javax.swing.JTextField txtproducto;
    public javax.swing.JTextField txttrabajador;
    // End of variables declaration//GEN-END:variables
}
