/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistema_inventarios;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorge
 */
public class TablaPro extends javax.swing.JPanel {

    /**
     * Creates new form TablaPro
     */
    public TablaPro() {
        initComponents();
        mostrarDatosEnTabla();
        // Agregar el ActionListener al botón ELIMINAR
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                eliminarDatoSeleccionado();
            }
        });
    }         
    private void mostrarDatosEnTabla() {
        // Obtener el modelo de la tabla
        DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();
        // Limpiar el modelo
        modeloTabla.setRowCount(0);

        // Conectar a la base de datos y recuperar los datos de la tabla "producto"
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventarios", "root", "")) {
            String query = "SELECT * FROM producto";
            try (PreparedStatement statement = connection.prepareStatement(query);
                 ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    // Obtener los datos de la fila
                    Object[] fila = {
                            resultSet.getString("codigo"),
                            resultSet.getString("nombre"),
                            resultSet.getString("categoria"),
                            resultSet.getString("descripcion"),
                             resultSet.getDouble("precio"),
                            resultSet.getString("pais"),
                    };
                    // Agregar la fila al modelo de la tabla
                    modeloTabla.addRow(fila);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Manejo de errores, log, etc.
        }
    }
     private void eliminarDatoSeleccionado() {
        int filaSeleccionada = tabla.getSelectedRow();
        if (filaSeleccionada != -1) { // Si hay una fila seleccionada
            // Obtener el modelo de la tabla
            DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();
            // Obtener el valor de la columna "Codigo" de la fila seleccionada
            String codigo = (String) modeloTabla.getValueAt(filaSeleccionada, 0);

            // Eliminar la fila de la tabla
            modeloTabla.removeRow(filaSeleccionada);

            // Eliminar el dato de la base de datos
            eliminarDatoDeBaseDeDatos(codigo);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
        }
    }

    private void eliminarDatoDeBaseDeDatos(String codigo) {
        // Conectar a la base de datos y realizar la eliminación
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventarios", "root", "")) {
            String query = "DELETE FROM producto WHERE codigo = ?";
            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, codigo);
                statement.executeUpdate();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Manejo de errores, log, etc.
        }
    }
    // </editor-fold>               
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(707, 430));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Descripcion", "Pais de Origen", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton2.setText("ELIMINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
